// Splits src/calcs/more.tsx into:
//   src/calcs/more-shared.ts          — shared top-level helpers/constants (exported)
//   src/calcs/more-waves/wave-N.tsx   — ~8 balanced chunks of calculator components
//   src/calcs/more-lazy.ts            — MORE_CALC_COMPONENTS registry of React.lazy wrappers
// The original more.tsx is preserved at scripts/more.tsx.bak and removed from src.
import { readFileSync, writeFileSync, mkdirSync, renameSync, rmSync, existsSync } from 'node:fs'

const SRC = 'src/calcs/more.tsx'
const src = readFileSync(SRC, 'utf8')
const lines = src.split('\n')

// --- registry (slug -> component name) ---
const regStart = lines.findIndex((l) => l.startsWith('export const MORE_CALC_COMPONENTS'))
if (regStart < 0) throw new Error('registry not found')
const registry = []
for (const l of lines.slice(regStart)) {
  const m = l.match(/^\s*'([^']+)':\s*(\w+),/)
  if (m) registry.push({ slug: m[1], comp: m[2] })
}

// --- body units ---
const body = lines.slice(0, regStart)
let headerEnd = 0
for (let i = 0; i < body.length; i++) if (body[i].startsWith('import ')) headerEnd = i + 1

const units = []
let pending = []
let cur = null
const flush = () => { if (cur) { units.push(cur); cur = null } }
for (let i = headerEnd; i < body.length; i++) {
  const l = body[i]
  const comp = l.match(/^export function (\w+)\(/)
  const helper = l.match(/^(?:function|const|type|interface) (\w+)/)
  if (comp || helper) {
    flush()
    cur = { kind: comp ? 'component' : 'helper', name: (comp || helper)[1], lines: [...pending, l] }
    pending = []
  } else if (cur) cur.lines.push(l)
  else pending.push(l)
}
flush()

const helpers = units.filter((u) => u.kind === 'helper')
const comps = units.filter((u) => u.kind === 'component')
const regComps = new Set(registry.map((r) => r.comp))
const missing = comps.filter((c) => !regComps.has(c.name)).map((c) => c.name)
if (missing.length) console.warn('components not in registry:', missing.join(', '))
console.log(`parsed: ${comps.length} components, ${helpers.length} helpers, ${registry.length} registry entries`)

// --- identifier usage scanner ---
const HEADER_IMPORTS = {
  react: ['useMemo', 'useState'],
  card: ['Card', 'CardContent'],
  index: ['useNumber', 'Field', 'Result'],
  calc: ['usd', 'num'],
  paycheck: ['FEDERAL', 'bracketTax', 'SS_WAGE_CAP'],
}
const helperNames = helpers.map((h) => h.name)
const uses = (text, name) => new RegExp(`\\b${name}\\b`).test(text)
const importsFor = (text, inSharedDir) => {
  const out = []
  const r = HEADER_IMPORTS.react.filter((n) => uses(text, n))
  if (r.length) out.push(`import { ${r.join(', ')} } from 'react'`)
  const c = HEADER_IMPORTS.card.filter((n) => uses(text, n))
  if (c.length) out.push(`import { ${c.join(', ')} } from '@/components/ui/card'`)
  const ix = HEADER_IMPORTS.index.filter((n) => uses(text, n))
  if (ix.length) out.push(`import { ${ix.join(', ')} } from '${inSharedDir ? '.' : '..'}/index'`)
  const cl = HEADER_IMPORTS.calc.filter((n) => uses(text, n))
  if (cl.length) out.push(`import { ${cl.join(', ')} } from '@/lib/calc'`)
  const p = HEADER_IMPORTS.paycheck.filter((n) => uses(text, n))
  if (p.length) out.push(`import { ${p.join(', ')} } from '@/data/paycheck'`)
  if (!inSharedDir) {
    const h = helperNames.filter((n) => uses(text, n))
    const typeHelpers = new Set(helpers.filter((x) => /^(?:type|interface) /.test(x.lines.join('\n').trimStart())).map((x) => x.name))
    const vals = h.filter((n) => !typeHelpers.has(n))
    const tys = h.filter((n) => typeHelpers.has(n))
    if (vals.length) out.push(`import { ${vals.join(', ')} } from '../more-shared'`)
    if (tys.length) out.push(`import type { ${tys.join(', ')} } from '../more-shared'`)
  }
  return out.join('\n')
}

// --- more-shared.ts ---
const sharedBody = helpers
  .map((h) => h.lines.join('\n').replace(/^(function|const|type|interface) /, 'export $1 '))
  .join('\n')
const sharedFile = `// Shared helpers/constants extracted from more.tsx by scripts/split-more.mjs
${importsFor(sharedBody, true)}

${sharedBody}
`
writeFileSync('src/calcs/more-shared.ts', sharedFile)

// --- waves: greedy byte-balance in file order ---
const N_WAVES = 8
const totalBytes = comps.reduce((s, c) => s + c.lines.join('\n').length, 0)
const target = totalBytes / N_WAVES
const waves = [[]]
let acc = 0
for (const c of comps) {
  const len = c.lines.join('\n').length
  if (acc >= target && waves.length < N_WAVES) { waves.push([]); acc = 0 }
  waves[waves.length - 1].push(c)
  acc += len
}
const compWave = new Map()
mkdirSync('src/calcs/more-waves', { recursive: true })
waves.forEach((wave, i) => {
  const text = wave.map((c) => c.lines.join('\n')).join('\n')
  writeFileSync(
    `src/calcs/more-waves/wave-${i + 1}.tsx`,
    `// Wave ${i + 1} of more.tsx — generated by scripts/split-more.mjs\n${importsFor(text, false)}\n${text}\n`,
  )
  for (const c of wave) compWave.set(c.name, i + 1)
  console.log(`wave-${i + 1}: ${wave.length} components, ${(text.length / 1024).toFixed(0)}KB src`)
})

// --- lazy registry ---
const lazyLines = registry.map(({ slug, comp }) => {
  const w = compWave.get(comp)
  if (!w) throw new Error(`no wave for ${comp}`)
  return `  '${slug}': lazy(() => import('./more-waves/wave-${w}').then((m) => ({ default: m.${comp} }))),`
})
writeFileSync(
  'src/calcs/more-lazy.ts',
  `// Lazy registry generated by scripts/split-more.mjs — each calculator loads its wave chunk on demand.
import { lazy } from 'react'
import type { ComponentType, LazyExoticComponent } from 'react'
import type { CalcProps } from './index'

export const MORE_CALC_COMPONENTS: Record<string, LazyExoticComponent<ComponentType<CalcProps>>> = {
${lazyLines.join('\n')}
}
`,
)

// --- archive original ---
mkdirSync('scripts', { recursive: true })
if (existsSync('scripts/more.tsx.bak')) rmSync('scripts/more.tsx.bak')
renameSync(SRC, 'scripts/more.tsx.bak')
console.log('more.tsx archived to scripts/more.tsx.bak — done')
